#!/bin/sh
# /etc/init.d/dyndns -- Start or stop Dynamic DNS service, see www.dyndns.org
# This is for Debian

PATH=/sbin:/bin:/usr/sbin:/usr/bin

NAME=dyndns
DESC="Client to dynamic DNS (DDNS) service providers"

PIDFILE=/var/run/$NAME.pid
DEFAULT=/etc/default/$NAME

# Don't run if not installed
test -x $DAEMON || exit 0

# Evaluate the config for the Debian scripts
run_daemon=false
interval=15m

if [ -f $DEFAULT ]; then
  . $DEFAULT || exit $?
fi

DAEMON="/usr/bin/$NAME"
OPTIONS="--daemon $interval --Config /etc/dyndns/*"

set -e

DaemonStart()
{
    echo -n "Starting $DESC: "

    start-stop-daemon --start --pidfile $PIDFILE \
    --exec $DAEMON $* -- $OPTIONS

    rm -f $PIDFILE

    echo "$NAME."
}

DaemonStop()
{
    if [ -f $PIDFILE ]; then

        echo -n "Stopping $DESC: "

        start-stop-daemon --stop --pidfile $PIDFILE \
        --oknodo --retry 30 --exec $DAEMON $* -- $OPTIONS

        echo "$NAME."
    else
        No pidfile found: $PIDFILE
    fi
}

function DaemonStatus()
{
    found=" [not exists]"
    regexp=$NAME

    if [ -f $PIDFILE ]; then
        found=""
        regexp=$PIDFILE
        pid=$(cat $PIDFILE)
        process=$(ps -p $pid)
    else
        process=$(ps -ef | egrep "PID|$NAME")
    fi

    echo "pidfile$found: $PIDFILE"
    echo $process
}

Main()
{
    case "$1" in
        start)
            [ "$run_daemon" != "true" ] && exit 0
            DaemonStart
            ;;

        stop)
            DaemonStop
            ;;

        reload)
            echo "$DESC: Nothing done. Reload is automatic at wake up interval."
            ;;

        restart|reload|force-reload)
            [ "$run_daemon" != "true" ] && exit 0

            echo "Restatring $DESC: "

            DaemonStop --quiet
            sleep 2
            DaemonStart

            echo "$NAME."
            ;;

        status)
            DaemonStatus
            ;;

        *)
            echo "Usage: $N" \
                 "{start|stop|restart|reload|force-reload|status}" >&2
            ;;
    esac
}

Main "$@"

# End of shell program
