#!/bin/sh
set -e

if [ $1 = purge ]; then 
    rm -f /etc/ddclient.conf
	rm -f /etc/default/ddclient
	rm -f /etc/ppp/ip-up.d/ddclient
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d ddclient remove >/dev/null
fi
# End automatically added section


exit 0

