#!/bin/sh
set -e

# Remove the cache file so that the directory can be deleted.
#
if [ "$1" = "remove" -o "$1" = "purge" ]; then
    rm -f /var/cache/ddclient/ddclient.cache
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/ddclient" ]; then
	if [ -x /usr/sbin/invoke-rc.d ] ; then
		invoke-rc.d ddclient stop
	else
		/etc/init.d/ddclient stop
	fi
fi
# End automatically added section


exit 0

